import { useState, useMemo } from 'react';

// Comprehensive list of Indian universities and colleges
export const INDIAN_UNIVERSITIES = [
  // IITs
  "Indian Institute of Technology (IIT) Delhi",
  "Indian Institute of Technology (IIT) Bombay",
  "Indian Institute of Technology (IIT) Madras",
  "Indian Institute of Technology (IIT) Kanpur",
  "Indian Institute of Technology (IIT) Kharagpur",
  "Indian Institute of Technology (IIT) Roorkee",
  "Indian Institute of Technology (IIT) Guwahati",
  "Indian Institute of Technology (IIT) Hyderabad",
  "Indian Institute of Technology (IIT) Indore",
  "Indian Institute of Technology (IIT) Varanasi (BHU)",
  "Indian Institute of Technology (IIT) Patna",
  "Indian Institute of Technology (IIT) Gandhinagar",
  "Indian Institute of Technology (IIT) Jodhpur",
  "Indian Institute of Technology (IIT) Mandi",
  "Indian Institute of Technology (IIT) Bhubaneswar",
  "Indian Institute of Technology (IIT) Tirupati",
  "Indian Institute of Technology (IIT) Dhanbad (ISM)",
  "Indian Institute of Technology (IIT) Bhilai",
  "Indian Institute of Technology (IIT) Goa",
  "Indian Institute of Technology (IIT) Jammu",
  "Indian Institute of Technology (IIT) Dharwad",
  "Indian Institute of Technology (IIT) Palakkad",
  
  // IISc and IISERs
  "Indian Institute of Science (IISc) Bangalore",
  "IISER Pune",
  "IISER Kolkata",
  "IISER Mohali",
  "IISER Bhopal",
  "IISER Thiruvananthapuram",
  "IISER Tirupati",
  "IISER Berhampur",
  
  // NITs
  "National Institute of Technology (NIT) Trichy",
  "National Institute of Technology (NIT) Warangal",
  "National Institute of Technology (NIT) Surathkal",
  "National Institute of Technology (NIT) Calicut",
  "National Institute of Technology (NIT) Rourkela",
  "National Institute of Technology (NIT) Kurukshetra",
  "National Institute of Technology (NIT) Durgapur",
  "National Institute of Technology (NIT) Allahabad",
  "National Institute of Technology (NIT) Jamshedpur",
  "National Institute of Technology (NIT) Nagpur",
  "National Institute of Technology (NIT) Surat",
  "National Institute of Technology (NIT) Silchar",
  "National Institute of Technology (NIT) Hamirpur",
  "National Institute of Technology (NIT) Jalandhar",
  "National Institute of Technology (NIT) Patna",
  "National Institute of Technology (NIT) Raipur",
  "National Institute of Technology (NIT) Agartala",
  "National Institute of Technology (NIT) Arunachal Pradesh",
  "National Institute of Technology (NIT) Delhi",
  "National Institute of Technology (NIT) Goa",
  "National Institute of Technology (NIT) Manipur",
  "National Institute of Technology (NIT) Meghalaya",
  "National Institute of Technology (NIT) Mizoram",
  "National Institute of Technology (NIT) Nagaland",
  "National Institute of Technology (NIT) Puducherry",
  "National Institute of Technology (NIT) Sikkim",
  "National Institute of Technology (NIT) Srinagar",
  "National Institute of Technology (NIT) Uttarakhand",
  "National Institute of Technology (NIT) Andhra Pradesh",
  "Motilal Nehru National Institute of Technology (MNNIT) Allahabad",
  "Maulana Azad National Institute of Technology (MANIT) Bhopal",
  "Visvesvaraya National Institute of Technology (VNIT) Nagpur",
  "Sardar Vallabhbhai National Institute of Technology (SVNIT) Surat",
  
  // IIITs
  "IIIT Hyderabad",
  "IIIT Delhi",
  "IIIT Bangalore",
  "IIIT Allahabad",
  "IIIT Gwalior",
  "IIIT Jabalpur",
  "IIIT Kancheepuram",
  "IIIT Lucknow",
  "IIIT Vadodara",
  "IIIT Kota",
  "IIIT Una",
  "IIIT Sonepat",
  "IIIT Nagpur",
  "IIIT Pune",
  "IIIT Ranchi",
  "IIIT Sri City",
  "IIIT Kalyani",
  "IIIT Dharwad",
  "IIIT Kottayam",
  "IIIT Manipur",
  "IIIT Tiruchirappalli",
  "IIIT Surat",
  "IIIT Bhopal",
  "IIIT Bhagalpur",
  "IIIT Agartala",
  "IIIT Raichur",
  
  // BITS
  "BITS Pilani",
  "BITS Pilani - Hyderabad Campus",
  "BITS Pilani - Goa Campus",
  "BITS Pilani - Dubai Campus",
  
  // Central Universities
  "Delhi University",
  "Jawaharlal Nehru University (JNU)",
  "Banaras Hindu University (BHU)",
  "Aligarh Muslim University (AMU)",
  "Jamia Millia Islamia",
  "University of Hyderabad",
  "Pondicherry University",
  "Central University of Kerala",
  "Central University of Tamil Nadu",
  "Central University of Karnataka",
  "Central University of Rajasthan",
  "Central University of Gujarat",
  "Central University of Punjab",
  "Central University of Haryana",
  "Central University of Himachal Pradesh",
  "Central University of Jammu",
  "Central University of Kashmir",
  "Central University of Jharkhand",
  "Central University of Odisha",
  "Central University of South Bihar",
  "Visva-Bharati University",
  "Tezpur University",
  "Assam University",
  "Tripura University",
  "Mizoram University",
  "Nagaland University",
  "Manipur University",
  "Sikkim University",
  "Rajiv Gandhi University",
  "North Eastern Hill University (NEHU)",
  "Mahatma Gandhi Central University",
  "Hemvati Nandan Bahuguna Garhwal University",
  "Babasaheb Bhimrao Ambedkar University",
  "Indira Gandhi National Tribal University",
  "Guru Ghasidas Vishwavidyalaya",
  "Dr. Harisingh Gour University",
  "Maulana Azad National Urdu University",
  "English and Foreign Languages University",
  
  // State Universities
  "Mumbai University",
  "Anna University",
  "Calcutta University",
  "Madras University",
  "Osmania University",
  "Savitribai Phule Pune University",
  "Bangalore University",
  "Gujarat University",
  "Rajasthan University",
  "Punjab University",
  "Jadavpur University",
  "Andhra University",
  "Kerala University",
  "Mysore University",
  "SNDT Women's University",
  "Amravati University",
  "Shivaji University",
  "Dr. Babasaheb Ambedkar Marathwada University",
  "North Maharashtra University",
  "Solapur University",
  "Rashtrasant Tukadoji Maharaj Nagpur University",
  "Gondwana University",
  "Kavayitri Bahinabai Chaudhari North Maharashtra University",
  "Swami Ramanand Teerth Marathwada University",
  "Mahatma Gandhi University, Kottayam",
  "Cochin University of Science and Technology (CUSAT)",
  "Kannur University",
  "Calicut University",
  "Bharathiar University",
  "Bharathidasan University",
  "Madurai Kamaraj University",
  "Manonmaniam Sundaranar University",
  "Periyar University",
  "Alagappa University",
  "Mother Teresa Women's University",
  "Tamil Nadu Open University",
  "Annamalai University",
  "SRM Institute of Science and Technology",
  "Vellore Institute of Technology (VIT)",
  "Manipal Academy of Higher Education",
  "Amity University",
  "Lovely Professional University",
  "Chandigarh University",
  "Shiv Nadar University",
  "Ashoka University",
  "O.P. Jindal Global University",
  "Azim Premji University",
  "FLAME University",
  "Krea University",
  "Plaksha University",
  "BML Munjal University",
  "Bennett University",
  "Symbiosis International University",
  "Christ University",
  "Jain University",
  "PES University",
  "RV University",
  "Dayananda Sagar University",
  "MS Ramaiah University",
  "KIIT University",
  "Kalinga Institute of Industrial Technology",
  "Xavier University Bhubaneswar",
  "SOA University",
  "GITAM University",
  "KL University",
  "Vignan University",
  "SRM University AP",
  "VIT-AP University",
  "Woxsen University",
  "Mahindra University",
  "ICFAI Foundation for Higher Education",
  "LPU - Lovely Professional University",
  "Chitkara University",
  "Thapar Institute of Engineering and Technology",
  "PEC University of Technology",
  "Punjab Engineering College",
  "Guru Nanak Dev University",
  "Panjab University",
  "Kurukshetra University",
  "Maharshi Dayanand University",
  "Deenbandhu Chhotu Ram University of Science and Technology",
  "J.C. Bose University of Science and Technology",
  "Guru Jambheshwar University of Science and Technology",
  "Chaudhary Devi Lal University",
  "Chaudhary Bansi Lal University",
  "Central University of South Bihar",
  "Nalanda University",
  "Patna University",
  "Magadh University",
  "Lalit Narayan Mithila University",
  "Tilka Manjhi Bhagalpur University",
  "Veer Kunwar Singh University",
  "B.R. Ambedkar Bihar University",
  "Jai Prakash University",
  "Ranchi University",
  "Birsa Agricultural University",
  "Vinoba Bhave University",
  "Kolhan University",
  "Sido Kanhu Murmu University",
  "Nilamber Pitamber University",
  "Dr. Shyama Prasad Mukherjee University",
  "Chhattisgarh Swami Vivekanand Technical University",
  "Pt. Ravishankar Shukla University",
  "Guru Ghasidas Vishwavidyalaya",
  "Indira Gandhi Krishi Vishwavidyalaya",
  "Kushabhau Thakre Patrakarita Avam Jansanchar Vishwavidyalaya",
  "Hidayatullah National Law University",
  "National Law University Delhi",
  "National Law School of India University (NLSIU) Bangalore",
  "NALSAR University of Law Hyderabad",
  "National Law University Jodhpur",
  "West Bengal National University of Juridical Sciences (NUJS)",
  "Gujarat National Law University",
  "Dr. Ram Manohar Lohiya National Law University",
  "Rajiv Gandhi National University of Law",
  "Chanakya National Law University",
  "National University of Advanced Legal Studies (NUALS)",
  "National Law University Odisha",
  "National University of Study and Research in Law (NUSRL)",
  "Damodaram Sanjivayya National Law University",
  "Tamil Nadu National Law University",
  "Maharashtra National Law University Mumbai",
  "Maharashtra National Law University Nagpur",
  "Maharashtra National Law University Aurangabad",
  "Himachal Pradesh National Law University",
  "Dharmashastra National Law University",
  
  // Medical and Health Universities
  "All India Institute of Medical Sciences (AIIMS) Delhi",
  "AIIMS Bhopal",
  "AIIMS Bhubaneswar",
  "AIIMS Jodhpur",
  "AIIMS Patna",
  "AIIMS Raipur",
  "AIIMS Rishikesh",
  "AIIMS Nagpur",
  "AIIMS Mangalagiri",
  "AIIMS Gorakhpur",
  "AIIMS Bathinda",
  "AIIMS Kalyani",
  "AIIMS Deoghar",
  "AIIMS Bilaspur",
  "AIIMS Rajkot",
  "AIIMS Madurai",
  "AIIMS Bibinagar",
  "JIPMER Puducherry",
  "PGIMER Chandigarh",
  "SGPGIMS Lucknow",
  "Christian Medical College (CMC) Vellore",
  "Christian Medical College (CMC) Ludhiana",
  "Armed Forces Medical College (AFMC) Pune",
  "Maulana Azad Medical College",
  "Lady Hardinge Medical College",
  "King George's Medical University",
  "Grant Medical College",
  "Seth GS Medical College",
  "BJ Medical College Pune",
  "Kasturba Medical College Manipal",
  "Kasturba Medical College Mangalore",
  "St. John's Medical College",
  "JSS Medical College",
  "Bangalore Medical College",
  "Madras Medical College",
  "Stanley Medical College",
  "Kilpauk Medical College",
  "Government Medical College Thiruvananthapuram",
  "Government Medical College Kozhikode",
  "Institute of Medical Sciences BHU",
  
  // Management Institutes
  "Indian Institute of Management (IIM) Ahmedabad",
  "Indian Institute of Management (IIM) Bangalore",
  "Indian Institute of Management (IIM) Calcutta",
  "Indian Institute of Management (IIM) Lucknow",
  "Indian Institute of Management (IIM) Kozhikode",
  "Indian Institute of Management (IIM) Indore",
  "Indian Institute of Management (IIM) Shillong",
  "Indian Institute of Management (IIM) Rohtak",
  "Indian Institute of Management (IIM) Ranchi",
  "Indian Institute of Management (IIM) Raipur",
  "Indian Institute of Management (IIM) Trichy",
  "Indian Institute of Management (IIM) Kashipur",
  "Indian Institute of Management (IIM) Udaipur",
  "Indian Institute of Management (IIM) Nagpur",
  "Indian Institute of Management (IIM) Visakhapatnam",
  "Indian Institute of Management (IIM) Bodh Gaya",
  "Indian Institute of Management (IIM) Amritsar",
  "Indian Institute of Management (IIM) Sambalpur",
  "Indian Institute of Management (IIM) Sirmaur",
  "Indian Institute of Management (IIM) Jammu",
  "Faculty of Management Studies (FMS) Delhi",
  "XLRI Jamshedpur",
  "SP Jain Institute of Management and Research",
  "Management Development Institute (MDI) Gurgaon",
  "Indian School of Business (ISB)",
  "NMIMS Mumbai",
  "MICA Ahmedabad",
  "IMT Ghaziabad",
  "Great Lakes Institute of Management",
  "TAPMI Manipal",
  "SIBM Pune",
  "SCMHRD Pune",
  "IIFT Delhi",
  "NITIE Mumbai",
  "IBS Hyderabad",
  "Amrita School of Business",
  "LIBA Chennai",
  "Xavier Institute of Management Bhubaneswar (XIMB)",
  "Xavier Labour Relations Institute (XLRI)",
  "Goa Institute of Management",
  "Mudra Institute of Communications Ahmedabad (MICA)",
  "Institute of Rural Management Anand (IRMA)",
  "Fore School of Management",
  "International Management Institute (IMI) Delhi",
  "Lal Bahadur Shastri Institute of Management (LBSIM)",
  "Birla Institute of Management Technology (BIMTECH)",
  "Welingkar Institute of Management",
  "KJ Somaiya Institute of Management",
  "Jamnalal Bajaj Institute of Management Studies (JBIMS)",
  "Narsee Monjee Institute of Management Studies",
  "Institute of Management Technology (IMT) Nagpur",
  "IFMR Chennai",
  "Alliance University",
  "Christ Institute of Management",
  
  // Engineering Colleges
  "College of Engineering Pune (COEP)",
  "Veermata Jijabai Technological Institute (VJTI)",
  "Sardar Patel College of Engineering (SPCE)",
  "Institute of Chemical Technology (ICT) Mumbai",
  "Walchand College of Engineering",
  "Government College of Engineering Aurangabad",
  "Government College of Engineering Karad",
  "Sinhgad College of Engineering",
  "MIT Pune",
  "Vishwakarma Institute of Technology (VIT) Pune",
  "Cummins College of Engineering for Women",
  "PICT Pune",
  "Symbiosis Institute of Technology",
  "BMS College of Engineering",
  "RV College of Engineering",
  "PES Institute of Technology",
  "MS Ramaiah Institute of Technology",
  "Sri Jayachamarajendra College of Engineering",
  "University Visvesvaraya College of Engineering",
  "Dayananda Sagar College of Engineering",
  "New Horizon College of Engineering",
  "BNM Institute of Technology",
  "RNS Institute of Technology",
  "CMR Institute of Technology",
  "RVCE Bangalore",
  "NIE Mysore",
  "NMAM Institute of Technology",
  "St. Joseph Engineering College",
  "Manipal Institute of Technology",
  "College of Engineering Guindy (CEG)",
  "PSG College of Technology",
  "Sri Sivasubramaniya Nadar College of Engineering",
  "Thiagarajar College of Engineering",
  "Kongu Engineering College",
  "Kumaraguru College of Technology",
  "Coimbatore Institute of Technology",
  "Government College of Technology Coimbatore",
  "Bannari Amman Institute of Technology",
  "Mepco Schlenk Engineering College",
  "Kamaraj College of Engineering and Technology",
  "Velammal Engineering College",
  "Rajalakshmi Engineering College",
  "St. Joseph's College of Engineering",
  "Sathyabama Institute of Science and Technology",
  "Saveetha Engineering College",
  "Easwari Engineering College",
  "Sri Venkateswara College of Engineering",
  "Jeppiaar Engineering College",
  "Panimalar Engineering College",
  "Prathyusha Engineering College",
  "JNTU Hyderabad",
  "JNTU Kakinada",
  "JNTU Anantapur",
  "Osmania University College of Engineering",
  "University College of Engineering Kakinada",
  "Chaitanya Bharathi Institute of Technology (CBIT)",
  "Vasavi College of Engineering",
  "CVR College of Engineering",
  "Gokaraju Rangaraju Institute of Engineering and Technology",
  "Malla Reddy Engineering College",
  "VNR Vignana Jyothi Institute of Engineering and Technology",
  "MVSR Engineering College",
  "Sreenidhi Institute of Science and Technology",
  "Vardhaman College of Engineering",
  "Vignan Institute of Technology and Science",
  "BVRIT Hyderabad",
  "MGIT Hyderabad",
  "Mahatma Gandhi Institute of Technology",
  "Stanley College of Engineering and Technology for Women",
  "Netaji Subhas University of Technology (NSUT)",
  "Delhi Technological University (DTU)",
  "Indraprastha Institute of Information Technology Delhi (IIIT-D)",
  "Jamia Millia Islamia Faculty of Engineering",
  "Ambedkar Institute of Advanced Communication Technologies",
  "Bharati Vidyapeeth's College of Engineering",
  "Maharaja Agrasen Institute of Technology",
  "Guru Tegh Bahadur Institute of Technology",
  "Maharaja Surajmal Institute of Technology",
  "Bhagwan Parshuram Institute of Technology",
  "HMR Institute of Technology and Management",
  "Indira Gandhi Delhi Technical University for Women",
  "Harcourt Butler Technical University",
  "Motilal Nehru National Institute of Technology Allahabad",
  "Indian Institute of Information Technology Allahabad",
  "Kamla Nehru Institute of Technology",
  "Institute of Engineering and Technology Lucknow",
  "Bundelkhand Institute of Engineering and Technology",
  "Birla Institute of Applied Sciences",
  "Graphic Era University",
  "DIT University",
  "University of Petroleum and Energy Studies (UPES)",
  "College of Engineering Roorkee",
  "Govind Ballabh Pant University of Agriculture and Technology",
  "Birla Institute of Technology Mesra",
  "BIT Sindri",
  "National Institute of Foundry and Forge Technology",
  "Bengal Engineering and Science University (now IIEST Shibpur)",
  "Indian Institute of Engineering Science and Technology (IIEST) Shibpur",
  "Heritage Institute of Technology",
  "Institute of Engineering and Management",
  "Techno India",
  "Kalyani Government Engineering College",
  "Jalpaiguri Government Engineering College",
  "Haldia Institute of Technology",
  "Meghnad Saha Institute of Technology",
  "Academy of Technology",
  "Narula Institute of Technology",
  "Netaji Subhash Engineering College",
  "Budge Budge Institute of Technology",
  "JIS College of Engineering",
  "Government College of Engineering and Textile Technology Serampore",
  "University Institute of Technology Burdwan",
  "Dr. BC Roy Engineering College",
  "Jalpaiguri Government Engineering College",
  "Murshidabad College of Engineering and Technology",
  "Government College of Engineering and Ceramic Technology",
  "Asansol Engineering College",
  "Michael Madhusudan Memorial College",
  "Techno Main Salt Lake",
  "Supreme Knowledge Foundation Group of Institutions",
  "University of Engineering and Management Kolkata",
  "Guru Nanak Institute of Technology",
  "Chandigarh Engineering College",
  "PEC Chandigarh",
  "Chitkara University",
  "LPU School of Engineering",
  "Thapar Institute of Engineering and Technology",
  "CGC Landran",
  "Rayat Bahra University",
  "Punjabi University",
  "IK Gujral Punjab Technical University",
  "DAV Institute of Engineering and Technology",
  "GNDEC Ludhiana",
  "BCET Gurdaspur",
  "CU Chail",
  "CT University",
  "Amritsar College of Engineering and Technology",
  "SLIET Longowal",
  
  // Polytechnics and Diploma Colleges
  "Government Polytechnic Mumbai",
  "Government Polytechnic Pune",
  "Veermata Jijabai Technological Institute (Polytechnic)",
  "Victoria Jubilee Technical Institute (VJTI Polytechnic)",
  "K.K. Wagh Polytechnic",
  "Cusrow Wadia Institute of Technology",
  "Dr. D.Y. Patil Polytechnic",
  "Pimpri Chinchwad Polytechnic",
  "A.C. Patil College of Engineering (Polytechnic)",
  "Government Polytechnic Delhi",
  "Government Polytechnic Chennai",
  "Government Polytechnic Bangalore",
  "Government Polytechnic Hyderabad",
  "Government Polytechnic Kolkata",
  "Government Polytechnic Ahmedabad",
  "Government Polytechnic Jaipur",
  "Government Polytechnic Lucknow",
  "Government Polytechnic Bhopal",
  "Government Polytechnic Patna",
  "Industrial Training Institute (ITI) Delhi",
  "ITI Mumbai",
  "ITI Chennai",
  "ITI Bangalore",
  "ITI Hyderabad",
  
  // Agricultural Universities
  "Indian Agricultural Research Institute (IARI)",
  "National Dairy Research Institute (NDRI)",
  "Indian Veterinary Research Institute (IVRI)",
  "Central Institute of Fisheries Education (CIFE)",
  "Punjab Agricultural University",
  "Tamil Nadu Agricultural University",
  "Anand Agricultural University",
  "Junagadh Agricultural University",
  "Navsari Agricultural University",
  "Sardarkrushinagar Dantiwada Agricultural University",
  "Kerala Agricultural University",
  "University of Agricultural Sciences Bangalore",
  "University of Agricultural Sciences Dharwad",
  "University of Agricultural Sciences Raichur",
  "University of Agricultural and Horticultural Sciences Shimoga",
  "Acharya N.G. Ranga Agricultural University",
  "Sri Venkateswara Veterinary University",
  "Professor Jayashankar Telangana State Agricultural University",
  "PV Narasimha Rao Telangana Veterinary University",
  "Odisha University of Agriculture and Technology",
  "Birsa Agricultural University",
  "Rajendra Agricultural University",
  "Bihar Agricultural University",
  "Dr. Rajendra Prasad Central Agricultural University",
  "Chandra Shekhar Azad University of Agriculture and Technology",
  "Narendra Deva University of Agriculture and Technology",
  "Sardar Vallabhbhai Patel University of Agriculture and Technology",
  "Sam Higginbottom University of Agriculture, Technology and Sciences",
  "GB Pant University of Agriculture and Technology",
  "VCSG Uttarakhand University of Horticulture and Forestry",
  "Maharana Pratap University of Agriculture and Technology",
  "Swami Keshwanand Rajasthan Agricultural University",
  "Sri Karan Narendra Agriculture University",
  "Agriculture University Jodhpur",
  "Agriculture University Kota",
  "Rajmata Vijayaraje Scindia Krishi Vishwa Vidyalaya",
  "Jawaharlal Nehru Krishi Vishwa Vidyalaya",
  "Nanaji Deshmukh Veterinary Science University",
  "Mahatma Phule Krishi Vidyapeeth",
  "Dr. Panjabrao Deshmukh Krishi Vidyapeeth",
  "Vasantrao Naik Marathwada Krishi Vidyapeeth",
  "Dr. Balasaheb Sawant Konkan Krishi Vidyapeeth",
  "CCS Haryana Agricultural University",
  "Lala Lajpat Rai University of Veterinary and Animal Sciences",
  "Chaudhary Sarwan Kumar Himachal Pradesh Krishi Vishvavidyalaya",
  "Sher-e-Kashmir University of Agricultural Sciences and Technology",
  "SKUAST Kashmir",
  "SKUAST Jammu",
  "Assam Agricultural University",
  "Central Agricultural University Imphal",
  "Dr. YS Parmar University of Horticulture and Forestry",
  
  // Other Institutes
  "Indian Statistical Institute (ISI) Kolkata",
  "Indian Statistical Institute (ISI) Bangalore",
  "Indian Statistical Institute (ISI) Delhi",
  "Chennai Mathematical Institute",
  "Institute of Mathematical Sciences",
  "Harish-Chandra Research Institute",
  "Tata Institute of Fundamental Research (TIFR)",
  "Raman Research Institute",
  "Saha Institute of Nuclear Physics",
  "Bose Institute",
  "SN Bose National Centre for Basic Sciences",
  "Inter-University Centre for Astronomy and Astrophysics (IUCAA)",
  "Physical Research Laboratory",
  "Vikram Sarabhai Space Centre",
  "Indian Space Research Organisation (ISRO)",
  "Defence Research and Development Organisation (DRDO)",
  "Bhabha Atomic Research Centre (BARC)",
  "Indira Gandhi Centre for Atomic Research",
  "Raja Ramanna Centre for Advanced Technology",
  "Variable Energy Cyclotron Centre",
  "Institute for Plasma Research",
  "National Institute of Oceanography",
  "National Centre for Biological Sciences",
  "Centre for Cellular and Molecular Biology",
  "Indian Institute of Chemical Biology",
  "National Chemical Laboratory",
  "Indian Institute of Toxicology Research",
  "Central Drug Research Institute",
  "Central Food Technological Research Institute",
  "Central Leather Research Institute",
  "Central Electrochemical Research Institute",
  "Central Salt and Marine Chemicals Research Institute",
  "National Metallurgical Laboratory",
  "Central Glass and Ceramic Research Institute",
  "Central Mechanical Engineering Research Institute",
  "Central Building Research Institute",
  "Central Road Research Institute",
  "National Environmental Engineering Research Institute",
  "Indian Institute of Petroleum",
  "CSIR-North East Institute of Science and Technology",
  "CSIR-Indian Institute of Integrative Medicine",
  "CSIR-Institute of Himalayan Bioresource Technology",
  "CSIR-Institute of Minerals and Materials Technology",
  "CSIR-Structural Engineering Research Centre",
  "CSIR-Central Scientific Instruments Organisation",
  "Indian Institute of Astrophysics",
  "Space Applications Centre",
  "National Remote Sensing Centre",
  "Indian Institute of Remote Sensing",
  "Forest Research Institute",
  "Wildlife Institute of India",
  "Indian Institute of Forest Management",
  "Indian Institute of Mass Communication",
  "Film and Television Institute of India",
  "Satyajit Ray Film and Television Institute",
  "National Institute of Design",
  "National Institute of Fashion Technology",
  "Industrial Design Centre IIT Bombay",
  "Srishti Manipal Institute of Art, Design and Technology",
  "Pearl Academy",
  "Indian Institute of Crafts and Design",
  "National Institute of Pharmaceutical Education and Research (NIPER)",
  "Jamia Hamdard",
  "Manipal College of Pharmaceutical Sciences",
  "JSS College of Pharmacy",
  "PSG College of Pharmacy",
  "Institute of Chemical Technology Mumbai",
  "Birla Institute of Technology and Science (Pharmacy)",
  "Government Pharmacy College",
  "L.M. College of Pharmacy",
  "Poona College of Pharmacy",
  "Bombay College of Pharmacy",
  "Delhi Institute of Pharmaceutical Sciences and Research",
  "Amity Institute of Pharmacy",
  "ISF College of Pharmacy",
  "Chitkara College of Pharmacy",
  "Lovely Professional University School of Pharmaceutical Sciences",
  "DIT University School of Pharmacy"
];

export const useCollegeSearch = (searchQuery: string, _state?: string) => {
  const filteredColleges = useMemo(() => {
    if (searchQuery.length < 2) {
      return [];
    }
    
    const query = searchQuery.toLowerCase();
    return INDIAN_UNIVERSITIES.filter(college => 
      college.toLowerCase().includes(query)
    ).slice(0, 50);
  }, [searchQuery]);

  return { 
    colleges: filteredColleges.map((college, index) => ({ 
      id: index, 
      college,
      state: '',
      district: ''
    })), 
    isLoading: false, 
    error: null 
  };
};

// Alias for backward compatibility
export const POPULAR_UNIVERSITIES = INDIAN_UNIVERSITIES.slice(0, 50);
